Feature: Add combined sensor sessions
aerosense-ai/aerosense-tools pull request #19
Opened 2023-03-01 00:37 UTC by time-trader

2023-03-01 12:17 UTC, cortadocodes requested changes
Looks good to me apart from missing docstrings

2023-03-01 12:17 UTC, cortadocodes commented on tests/test_pre_process.py
> +class TestPreProcess(unittest.TestCase):
Could you add docstrings to each method and each test?

2023-03-01 12:17 UTC, cortadocodes commented on tests/test_pre_process.py
> +
Excess whitespace

2023-03-02 23:53 UTC, time-trader commented
> Looks good to me apart from missing docstrings

Done. Thank you for the review.

2023-03-06 15:42 UTC, merged